#!/usr/bin/bash

if [ "$#" -ne 2 ]; then
    PKG_FOLDER=$(pwd)
    TENSORBOARD_LOGS_FOLDER="$(pwd)/tensorboard_logs"
else
    PKG_FOLDER=$1
    TENSORBOARD_LOGS_FOLDER=$2
fi

#nvidia-docker run -it --rm \
xhost +
optirun -b primus nvidia-docker run -it --rm \
    -v $PKG_FOLDER:/workspace/sandbox \
    -v $TENSORBOARD_LOGS_FOLDER:/workspace/runs \
    -v $(readlink ./nf):/workspace/nf \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=$DISPLAY \
    -p 6006:6006 \
    -p 8888:8888 \
    colobas/dl-sandbox \
    /bin/bash -c "\
    cd sandbox && \
    tmux -2 new-session -d -s sandbox && \
    tmux new-window -t sandbox:1 -n 'tensorboard' && \
    tmux select-window -t sandbox:1 && \
    tmux send-keys 'cd ..' C-m && \
    tmux send-keys 'tensorboard --logdir runs' C-m  && \
    tmux new-window -t sandbox:2 -n 'jupyter' && \
    tmux select-window -t sandbox:2 && \
    tmux send-keys 'jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=\"\"' C-m && \
    tmux select-window -t sandbox:0 && \

    /bin/bash -c 'tmux a -t sandbox'"

xhost -
