#!/usr/bin/bash

if [ "$#" -ne 2 ]; then
    PKG_FOLDER=/home/colobas/dev/guilhermepires-thesis
    TENSORBOARD_LOGS_FOLDER=/home/colobas/dev/tensorboard_logs
else
    PKG_FOLDER=$1
    TENSORBOARD_LOGS_FOLDER=$2
fi

xhost +
optirun -b primus sudo nvidia-docker run -it --rm \
    -v $PKG_FOLDER:/workspace/thesis \
    -v $TENSORBOARD_LOGS_FOLDER:/workspace/runs\
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=$DISPLAY \
    -p 6006:6006 \
    colobas/thesis \
    /bin/bash -c "\
    cd thesis && \
    pip install -e . && \
    tmux -2 new-session -d -s thesis && \
    tmux new-window -t thesis:1 -n 'tensorboard' && \
    tmux select-window -t thesis:1 && \
    tmux send-keys 'cd ..' C-m && \
    tmux send-keys 'tensorboard --logdir runs' C-m  && \
    tmux select-window -t thesis:0 && \

    /bin/bash -c 'tmux a -t thesis'"
xhost -
